// Mock data for MAILOPS AI - used when Firestore data is unavailable
// This provides realistic sample data for all application views

export const mockEmails = [
  {
    id: 'email-001',
    from: 'accounts@acmecorp.com',
    fromName: 'ACME Corp Billing',
    to: 'finance@yourcompany.com',
    subject: 'Invoice #INV-2024-0847 - Payment Due March 15',
    body: 'Dear Team,\n\nPlease find attached Invoice #INV-2024-0847 for services rendered in February 2024. The total amount due is $12,450.00.\n\nPayment Terms: Net 30\nDue Date: March 15, 2024\n\nPlease process this at your earliest convenience.\n\nBest regards,\nACME Corp Billing Department',
    receivedAt: '2024-03-01T09:15:00Z',
    status: 'processed',
    intent: 'invoice',
    confidence: 96,
    handler: 'invoice',
    action: 'automated',
    policyDecision: 'auto_approve',
    policyReason: 'Confidence above threshold (96% > 85%). Known vendor. Amount within auto-approve limit.',
    amount: 12450.00,
    invoiceNumber: 'INV-2024-0847',
    vendor: 'ACME Corp',
    priority: 'medium',
    labels: ['invoice', 'vendor', 'auto-processed'],
  },
  {
    id: 'email-002',
    from: 'john.smith@clientxyz.com',
    fromName: 'John Smith',
    to: 'support@yourcompany.com',
    subject: 'Dispute: Incorrect charge on account #AC-5521',
    body: 'Hi Support,\n\nI noticed an incorrect charge of $2,340.00 on my account #AC-5521 dated February 28, 2024. This charge does not match any of our agreed services.\n\nPlease investigate and correct this issue as soon as possible. I have attached the original agreement for reference.\n\nRegards,\nJohn Smith\nClient XYZ',
    receivedAt: '2024-03-01T10:30:00Z',
    status: 'processed',
    intent: 'dispute',
    confidence: 92,
    handler: 'dispute',
    action: 'human_review',
    policyDecision: 'escalate',
    policyReason: 'Dispute requires human review per policy. Customer tier: Premium. Amount: $2,340.00.',
    amount: 2340.00,
    accountNumber: 'AC-5521',
    priority: 'high',
    labels: ['dispute', 'premium-client', 'escalated'],
  },
  {
    id: 'email-003',
    from: 'payments@stripe.com',
    fromName: 'Stripe Payments',
    to: 'finance@yourcompany.com',
    subject: 'Payment Confirmation - $8,750.00 received',
    body: 'Payment Received\n\nA payment of $8,750.00 has been successfully processed.\n\nTransaction ID: txn_3MqX2F4Jk9L\nDate: March 1, 2024\nFrom: TechStart Inc.\nMethod: ACH Bank Transfer\n\nThis payment has been credited to your Stripe account.\n\nThank you,\nStripe Team',
    receivedAt: '2024-03-01T11:45:00Z',
    status: 'processed',
    intent: 'payment_confirmation',
    confidence: 99,
    handler: 'payment',
    action: 'automated',
    policyDecision: 'auto_approve',
    policyReason: 'Payment confirmation from verified processor. Confidence: 99%. Auto-logged.',
    amount: 8750.00,
    transactionId: 'txn_3MqX2F4Jk9L',
    priority: 'low',
    labels: ['payment', 'confirmed', 'auto-processed'],
  },
  {
    id: 'email-004',
    from: 'billing@cloudservices.io',
    fromName: 'Cloud Services Billing',
    to: 'finance@yourcompany.com',
    subject: 'Invoice #CS-7721 - Monthly Infrastructure',
    body: 'Hello,\n\nYour monthly infrastructure invoice is ready.\n\nInvoice: #CS-7721\nPeriod: February 1-28, 2024\nAmount: $3,200.00\nDue: March 20, 2024\n\nServices:\n- Compute instances: $1,800.00\n- Storage: $450.00\n- Bandwidth: $650.00\n- Support: $300.00\n\nView your full invoice at: dashboard.cloudservices.io\n\nCloud Services Billing Team',
    receivedAt: '2024-03-01T14:20:00Z',
    status: 'processed',
    intent: 'invoice',
    confidence: 94,
    handler: 'invoice',
    action: 'automated',
    policyDecision: 'auto_approve',
    policyReason: 'Recurring vendor invoice. Confidence: 94%. Amount within expected range.',
    amount: 3200.00,
    invoiceNumber: 'CS-7721',
    vendor: 'Cloud Services',
    priority: 'medium',
    labels: ['invoice', 'recurring', 'auto-processed'],
  },
  {
    id: 'email-005',
    from: 'sarah.jones@megaclient.com',
    fromName: 'Sarah Jones',
    to: 'ar@yourcompany.com',
    subject: 'RE: Outstanding Balance - Request for Payment Plan',
    body: 'Dear Accounts Receivable,\n\nRegarding our outstanding balance of $45,000.00, we would like to request a payment plan arrangement. We propose splitting this into 3 monthly payments of $15,000.00.\n\nOur company is going through a restructuring and we want to ensure all obligations are met.\n\nPlease let me know if this arrangement is acceptable.\n\nBest regards,\nSarah Jones\nCFO, MegaClient Inc.',
    receivedAt: '2024-03-01T16:00:00Z',
    status: 'pending',
    intent: 'payment_request',
    confidence: 78,
    handler: 'payment',
    action: 'human_review',
    policyDecision: 'escalate',
    policyReason: 'Payment plan request requires approval. Confidence below auto-threshold (78% < 85%). Large amount: $45,000.',
    amount: 45000.00,
    priority: 'high',
    labels: ['payment', 'payment-plan', 'needs-review'],
  },
  {
    id: 'email-006',
    from: 'noreply@bankofamerica.com',
    fromName: 'Bank of America',
    to: 'finance@yourcompany.com',
    subject: 'Wire Transfer Received - $25,000.00',
    body: 'Wire Transfer Notification\n\nA wire transfer has been received and posted to your account.\n\nAmount: $25,000.00\nSender: Global Partners LLC\nReference: WR-2024-03-001\nDate: March 1, 2024\n\nYour updated balance will reflect within 24 hours.\n\nBank of America N.A.',
    receivedAt: '2024-03-02T08:00:00Z',
    status: 'processed',
    intent: 'payment_confirmation',
    confidence: 97,
    handler: 'payment',
    action: 'automated',
    policyDecision: 'auto_approve',
    policyReason: 'Wire transfer notification from verified bank. Confidence: 97%. Auto-logged.',
    amount: 25000.00,
    priority: 'low',
    labels: ['payment', 'wire-transfer', 'auto-processed'],
  },
  {
    id: 'email-007',
    from: 'mike.chen@deltaworks.com',
    fromName: 'Mike Chen',
    to: 'support@yourcompany.com',
    subject: 'Billing Dispute - Double Charged for Q1 License',
    body: 'To whom it may concern,\n\nWe have been double-charged for our Q1 2024 enterprise license.\n\nCharge 1: $18,500.00 on Feb 1, 2024\nCharge 2: $18,500.00 on Feb 15, 2024\n\nOnly one charge should have been processed. Please refund the duplicate charge of $18,500.00 immediately.\n\nAccount: ENT-8834\nCompany: DeltaWorks Inc.\n\nMike Chen\nHead of Procurement',
    receivedAt: '2024-03-02T09:30:00Z',
    status: 'processed',
    intent: 'dispute',
    confidence: 95,
    handler: 'dispute',
    action: 'human_review',
    policyDecision: 'escalate',
    policyReason: 'Duplicate charge dispute. High amount ($18,500). Enterprise client. Requires human verification.',
    amount: 18500.00,
    priority: 'high',
    labels: ['dispute', 'duplicate-charge', 'enterprise'],
  },
  {
    id: 'email-008',
    from: 'vendor@officesupply.com',
    fromName: 'Office Supply Pro',
    to: 'procurement@yourcompany.com',
    subject: 'Invoice #OSP-4412 - Office Supplies Order',
    body: 'Dear Customer,\n\nThank you for your order. Please find your invoice below.\n\nInvoice: #OSP-4412\nDate: March 2, 2024\nDue: March 17, 2024\n\nItems:\n- Printer Paper (10 cases): $280.00\n- Toner Cartridges (6): $540.00\n- Office Chairs (2): $890.00\n\nSubtotal: $1,710.00\nTax: $136.80\nTotal: $1,846.80\n\nOffice Supply Pro',
    receivedAt: '2024-03-02T11:15:00Z',
    status: 'processed',
    intent: 'invoice',
    confidence: 93,
    handler: 'invoice',
    action: 'automated',
    policyDecision: 'auto_approve',
    policyReason: 'Standard vendor invoice. Amount within auto-approve limit. Confidence: 93%.',
    amount: 1846.80,
    invoiceNumber: 'OSP-4412',
    vendor: 'Office Supply Pro',
    priority: 'low',
    labels: ['invoice', 'supplies', 'auto-processed'],
  },
  {
    id: 'email-009',
    from: 'lisa.park@newclient.com',
    fromName: 'Lisa Park',
    to: 'sales@yourcompany.com',
    subject: 'Question about pricing and payment options',
    body: 'Hello,\n\nWe are interested in your Enterprise plan and would like to understand the pricing structure and available payment options.\n\nSpecifically:\n1. Is annual billing available?\n2. Do you offer volume discounts for 500+ users?\n3. What payment methods do you accept?\n\nWe are looking to onboard in Q2 2024.\n\nThank you,\nLisa Park\nVP Operations, NewClient Corp',
    receivedAt: '2024-03-02T13:45:00Z',
    status: 'pending',
    intent: 'inquiry',
    confidence: 72,
    handler: 'payment',
    action: 'human_review',
    policyDecision: 'route_to_sales',
    policyReason: 'General inquiry about pricing. Confidence: 72%. Routed to sales team for follow-up.',
    priority: 'medium',
    labels: ['inquiry', 'sales-lead', 'needs-review'],
  },
  {
    id: 'email-010',
    from: 'compliance@regulator.gov',
    fromName: 'Regulatory Compliance',
    to: 'legal@yourcompany.com',
    subject: 'Annual Compliance Audit - Document Request',
    body: 'Dear Compliance Officer,\n\nAs part of the annual regulatory compliance audit, we require the following documentation by March 31, 2024:\n\n1. Financial statements for FY 2023\n2. Transaction records for Q3-Q4 2023\n3. Internal audit reports\n4. Data processing agreements\n\nPlease ensure all documents are submitted through the secure portal.\n\nRegulatory Compliance Division',
    receivedAt: '2024-03-02T15:00:00Z',
    status: 'pending',
    intent: 'compliance',
    confidence: 65,
    handler: 'dispute',
    action: 'human_review',
    policyDecision: 'escalate',
    policyReason: 'Regulatory compliance request. Low confidence for automated handling (65%). Requires legal team review.',
    priority: 'high',
    labels: ['compliance', 'regulatory', 'urgent'],
  },
];

export const mockAuditLogs = [
  {
    id: 'audit-001',
    emailId: 'email-001',
    action: 'auto_processed',
    handler: 'invoice',
    description: 'Invoice #INV-2024-0847 from ACME Corp automatically processed and queued for payment.',
    confidence: 96,
    timestamp: '2024-03-01T09:15:30Z',
    performedBy: 'system',
    status: 'completed',
  },
  {
    id: 'audit-002',
    emailId: 'email-002',
    action: 'escalated',
    handler: 'dispute',
    description: 'Dispute from John Smith (Client XYZ) escalated to human review team.',
    confidence: 92,
    timestamp: '2024-03-01T10:31:00Z',
    performedBy: 'system',
    status: 'pending_review',
  },
  {
    id: 'audit-003',
    emailId: 'email-003',
    action: 'auto_logged',
    handler: 'payment',
    description: 'Payment confirmation of $8,750.00 from Stripe automatically logged.',
    confidence: 99,
    timestamp: '2024-03-01T11:45:15Z',
    performedBy: 'system',
    status: 'completed',
  },
  {
    id: 'audit-004',
    emailId: 'email-004',
    action: 'auto_processed',
    handler: 'invoice',
    description: 'Monthly invoice #CS-7721 from Cloud Services automatically processed.',
    confidence: 94,
    timestamp: '2024-03-01T14:20:10Z',
    performedBy: 'system',
    status: 'completed',
  },
  {
    id: 'audit-005',
    emailId: 'email-005',
    action: 'escalated',
    handler: 'payment',
    description: 'Payment plan request from Sarah Jones (MegaClient) escalated for manager approval.',
    confidence: 78,
    timestamp: '2024-03-01T16:00:30Z',
    performedBy: 'system',
    status: 'pending_review',
  },
  {
    id: 'audit-006',
    emailId: 'email-006',
    action: 'auto_logged',
    handler: 'payment',
    description: 'Wire transfer of $25,000.00 from Global Partners LLC automatically recorded.',
    confidence: 97,
    timestamp: '2024-03-02T08:00:20Z',
    performedBy: 'system',
    status: 'completed',
  },
  {
    id: 'audit-007',
    emailId: 'email-007',
    action: 'escalated',
    handler: 'dispute',
    description: 'Double charge dispute from Mike Chen (DeltaWorks) flagged for urgent review.',
    confidence: 95,
    timestamp: '2024-03-02T09:30:15Z',
    performedBy: 'system',
    status: 'pending_review',
  },
  {
    id: 'audit-008',
    emailId: 'email-008',
    action: 'auto_processed',
    handler: 'invoice',
    description: 'Office supplies invoice #OSP-4412 automatically approved and queued.',
    confidence: 93,
    timestamp: '2024-03-02T11:15:10Z',
    performedBy: 'system',
    status: 'completed',
  },
  {
    id: 'audit-009',
    emailId: 'email-002',
    action: 'reviewed',
    handler: 'dispute',
    description: 'Dispute from John Smith reviewed by agent. Refund approved for $2,340.00.',
    confidence: 92,
    timestamp: '2024-03-02T14:00:00Z',
    performedBy: 'agent@yourcompany.com',
    status: 'resolved',
  },
  {
    id: 'audit-010',
    emailId: 'email-009',
    action: 'routed',
    handler: 'payment',
    description: 'Pricing inquiry from Lisa Park routed to sales team for follow-up.',
    confidence: 72,
    timestamp: '2024-03-02T13:45:30Z',
    performedBy: 'system',
    status: 'in_progress',
  },
];

export const mockHandlers = [
  {
    id: 'handler-invoice',
    name: 'Invoice Handler',
    type: 'invoice',
    description: 'Processes incoming invoices, extracts key data, validates against vendor records, and queues for payment.',
    status: 'active',
    totalProcessed: 156,
    autoRate: 89,
    avgConfidence: 94,
  },
  {
    id: 'handler-payment',
    name: 'Payment Handler',
    type: 'payment',
    description: 'Handles payment confirmations, wire transfers, and payment-related inquiries. Logs transactions automatically.',
    status: 'active',
    totalProcessed: 203,
    autoRate: 76,
    avgConfidence: 88,
  },
  {
    id: 'handler-dispute',
    name: 'Dispute Handler',
    type: 'dispute',
    description: 'Manages billing disputes, refund requests, and charge corrections. Most cases are escalated for human review.',
    status: 'active',
    totalProcessed: 47,
    autoRate: 15,
    avgConfidence: 82,
  },
];

export const mockPolicies = [
  {
    id: 'policy-001',
    name: 'Auto-Approve Threshold',
    description: 'Emails with AI confidence above this threshold are automatically processed without human review.',
    type: 'confidence',
    value: 85,
    unit: '%',
    status: 'active',
  },
  {
    id: 'policy-002',
    name: 'Maximum Auto-Approve Amount',
    description: 'Invoices above this amount require human approval regardless of confidence score.',
    type: 'amount',
    value: 50000,
    unit: 'USD',
    status: 'active',
  },
  {
    id: 'policy-003',
    name: 'Dispute Auto-Escalation',
    description: 'All dispute-classified emails are automatically escalated for human review.',
    type: 'handler',
    value: 'always_escalate',
    handler: 'dispute',
    status: 'active',
  },
  {
    id: 'policy-004',
    name: 'New Vendor Review',
    description: 'Invoices from unrecognized vendors are flagged for manual verification.',
    type: 'vendor',
    value: 'review_new',
    status: 'active',
  },
  {
    id: 'policy-005',
    name: 'Regulatory Compliance Flag',
    description: 'Emails classified as compliance-related are routed to the legal team.',
    type: 'routing',
    value: 'legal_team',
    status: 'active',
  },
];

// Helper to get mock dashboard stats
export function getMockDashboardStats() {
  const emails = mockEmails;
  const totalEmails = emails.length;
  const processedEmails = emails.filter((e) => e.status === 'processed').length;
  const automatedActions = emails.filter((e) => e.action === 'automated').length;
  const humanReviews = emails.filter((e) => e.action === 'human_review').length;
  const avgConfidence = Math.round(
    emails.reduce((sum, e) => sum + (e.confidence || 0), 0) / totalEmails
  );

  return {
    totalEmails,
    processedEmails,
    automatedActions,
    humanReviews,
    avgConfidence,
    recentEmails: emails.slice(0, 5),
    recentAudit: mockAuditLogs.slice(0, 5),
  };
}
